crm/urls.py
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/', include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),
]

handler404 = handler404
handler500 = handler500

leads/urls.py
from django.urls import path
from leads.views import (
    LeadListView, CreateLeadView, LeadDetailView, UpdateLeadView, DeleteLeadView, ConvertLeadView,
    GetLeadsView, AddCommentView, UpdateCommentView, DeleteCommentView)


app_name = 'leads'


urlpatterns = [
    path('list/', LeadListView.as_view(), name='list'),
    path('create/', CreateLeadView.as_view(), name='add_lead'),
    path('<int:pk>/view/', LeadDetailView.as_view(), name="view_lead"),
    path('<int:pk>/edit/', UpdateLeadView.as_view(), name="edit_lead"),
    path('<int:pk>/delete/', DeleteLeadView.as_view(), name="remove_lead"),
    path('<int:pk>/convert/', ConvertLeadView.as_view(), name="leads_convert"),

    path('get/list/', GetLeadsView.as_view(), name="get_lead"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),
]

cases/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from accounts.models import Account
from contacts.models import Contact
from common.models import User, Team
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE


class Case(models.Model):
    name = models.CharField(
        pgettext_lazy("Name of the case", "Name"),
        max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(choices=CASE_TYPE, max_length=255, blank=True, null=True, default='')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_on = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='case_assigned_users')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='case_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting", status="Planned")

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Task", status="Planned")

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task").exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Call", status="Planned")

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

leads/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _

from accounts.models import Account
from common.models import User, Address, Team
from common.utils import LEAD_STATUS, LEAD_SOURCE


class Lead(models.Model):
    title = models.CharField(
        pgettext_lazy("Treatment Pronouns for the customer", "Title"),
        max_length=64, blank=True, null=True)
    first_name = models.CharField(("First name"), max_length=255)
    last_name = models.CharField(("Last name"), max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True, blank=True)
    account = models.ForeignKey(Account, related_name='Leads', on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(_("Status of Lead"), max_length=255,
                              blank=True, null=True, choices=LEAD_STATUS)
    source = models.CharField(_("Source of Lead"), max_length=255,
                              blank=True, null=True, choices=LEAD_SOURCE)
    address = models.ForeignKey(Address, related_name='leadaddress', on_delete=models.CASCADE, null=True, blank=True)
    website = models.CharField(_("Website"), max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='lead_assigned_users')
    teams = models.ManyToManyField(Team)
    account_name = models.CharField(max_length=255, null=True, blank=True)
    opportunity_amount = models.DecimalField(
        _("Opportunity Amount"), decimal_places=2, max_digits=12,
        blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)
    enquery_type = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering =['-created_on']

    def __str__(self):
        return self.first_name + self.last_name

leads/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.forms.models import modelformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import (
    CreateView, UpdateView, DetailView, ListView, TemplateView, View)

from accounts.models import Account
from common.forms import BillingAddressForm
from common.models import User, Comment, Team
from common.utils import LEAD_STATUS, LEAD_SOURCE, COUNTRIES
from leads.models import Lead
from leads.forms import LeadCommentForm, LeadForm
from planner.models import Event, Reminder
from planner.forms import ReminderForm


class LeadListView(LoginRequiredMixin, TemplateView):
    model = Lead
    context_object_name = "lead_obj"
    template_name = "leads.html"

    def get_queryset(self):
        queryset = self.model.objects.all().exclude(status='converted')
        request_post = self.request.POST
        if request_post:
            if request_post.get('first_name'):
                queryset = queryset.filter(first_name__icontains=request_post.get('first_name'))
            if request_post.get('last_name'):
                queryset = queryset.filter(last_name__icontains=request_post.get('last_name'))
            if request_post.get('city'):
                queryset = queryset.filter(address__city__icontains=request_post.get('city'))
            if request_post.get('email'):
                queryset = queryset.filter(email__icontains=request_post.get('email'))
            if request_post.get('status'):
                queryset = queryset.filter(status=request_post.get('status'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        context["lead_obj"] = self.get_queryset()
        context["status"] = LEAD_STATUS
        context["per_page"] = self.request.POST.get('per_page')
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class CreateLeadView(LoginRequiredMixin, CreateView):
    model = Lead
    form_class = LeadForm
    template_name = "create_lead.html"

    def dispatch(self, request, *args, **kwargs):
        self.users = User.objects.filter(is_active=True).order_by('email')
        return super(CreateLeadView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(CreateLeadView, self).get_form_kwargs()
        kwargs.update({"assigned_to": self.users})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        address_form = BillingAddressForm(request.POST)
        if form.is_valid() and address_form.is_valid():
            return self.form_valid(form, address_form)
        else:
            return self.form_invalid(form, address_form)

    def form_valid(self, form, address_form):
        address_object = address_form.save()
        lead_obj = form.save(commit=False)
        lead_obj.address = address_object
        lead_obj.created_by = self.request.user
        lead_obj.save()
        if self.request.POST.getlist('assigned_to', []):
            lead_obj.assigned_to.add(*self.request.POST.getlist('assigned_to'))
        if self.request.POST.getlist('teams', []):
            lead_obj.teams.add(*self.request.POST.getlist('teams'))

        if self.request.POST.get('status') == "converted":
            account_object = Account.objects.create(
                created_by=self.request.user, name=lead_obj.account_name,
                email=lead_obj.email, phone=lead_obj.phone,
                description=self.request.POST.get('description'),
                website=self.request.POST.get('website')
            )
            account_object.billing_address = address_object
            if self.request.POST.getlist('assigned_to', []):
                account_object.assigned_to.add(*self.request.POST.getlist('assigned_to'))
            if self.request.POST.getlist('teams', []):
                account_object.teams.add(*self.request.POST.getlist('teams'))
            account_object.save()
        if self.request.POST.get("savenewform"):
            return redirect("leads:add_lead")
        else:
            return redirect('leads:list')

    def form_invalid(self, form, address_form):
        return self.render_to_response(
            self.get_context_data(form=form, address_form=address_form))

    def get_context_data(self, **kwargs):
        context = super(CreateLeadView, self).get_context_data(**kwargs)
        context["lead_form"] = context["form"]
        context["teams"] = Team.objects.all()
        context["accounts"] = Account.objects.all()
        context["users"] = self.users
        context["countries"] = COUNTRIES
        context["status"] = LEAD_STATUS
        context["source"] = LEAD_SOURCE
        context["assignedto_list"] = [
            int(i) for i in self.request.POST.getlist('assigned_to', []) if i]
        context["teams_list"] = [
            int(i) for i in self.request.POST.getlist('teams', []) if i]
        if "address_form" in kwargs:
            context["address_form"] = kwargs["address_form"]
        else:
            if self.request.POST:
                context["address_form"] = BillingAddressForm(self.request.POST)
            else:
                context["address_form"] = BillingAddressForm()
        return context


class LeadDetailView(LoginRequiredMixin, DetailView):
    model = Lead
    context_object_name = "lead_record"
    template_name = "view_leads.html"

    def get_context_data(self, **kwargs):
        context = super(LeadDetailView, self).get_context_data(**kwargs)
        comments = Comment.objects.filter(lead__id=self.object.id).order_by('-id')
        events = Event.objects.filter(
            Q(created_by=self.request.user) | Q(updated_by=self.request.user)
        ).filter(attendees_leads=context["lead_record"])
        meetings = events.filter(event_type='Meeting').order_by('-id')
        calls = events.filter(event_type='Call').order_by('-id')
        RemindersFormSet = modelformset_factory(Reminder, form=ReminderForm, can_delete=True)
        reminder_form_set = RemindersFormSet({
            'form-TOTAL_FORMS': '1',
            'form-INITIAL_FORMS': '0',
            'form-MAX_NUM_FORMS': '10',
        })
        context.update({
            "comments": comments, "status": LEAD_STATUS, "countries": COUNTRIES,
            "reminder_form_set": reminder_form_set, "meetings": meetings, "calls": calls})
        return context


class UpdateLeadView(LoginRequiredMixin, UpdateView):
    model = Lead
    form_class = LeadForm
    template_name = "create_lead.html"

    def dispatch(self, request, *args, **kwargs):
        self.error = ""
        self.users = User.objects.filter(is_active=True).order_by('email')
        return super(UpdateLeadView, self).dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super(UpdateLeadView, self).get_initial()
        status = self.request.GET.get('status', None)
        if status:
            initial.update({"status": status})
        return initial

    def get_form_kwargs(self):
        kwargs = super(UpdateLeadView, self).get_form_kwargs()
        kwargs.update({"assigned_to": self.users})
        return kwargs

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        status = request.GET.get('status', None)
        if status:
            self.error = "This field is required."
            self.object.status = "converted"
        return super(UpdateLeadView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        address_obj = self.object.address
        form = self.get_form()
        address_form = BillingAddressForm(request.POST, instance=address_obj)
        if request.POST.get('status') == "converted":
            form.fields['account_name'].required = True
        else:
            form.fields['account_name'].required = False
        if form.is_valid() and address_form.is_valid():
            return self.form_valid(form, address_form)
        else:
            return self.form_invalid(form, address_form)

    def form_valid(self, form, address_form):
        address_obj = address_form.save()
        lead_obj = form.save(commit=False)
        lead_obj.address = address_obj
        lead_obj.save()
        lead_obj.assigned_to.clear()
        lead_obj.teams.clear()
        if self.request.POST.getlist('assigned_to', []):
            lead_obj.assigned_to.add(*self.request.POST.getlist('assigned_to'))
        if self.request.POST.getlist('teams', []):
            lead_obj.teams.add(*self.request.POST.getlist('teams'))
        if self.request.POST.get('status') == "converted":
            account_object = Account.objects.create(
                created_by=self.request.user, name=lead_obj.account_name,
                email=lead_obj.email, phone=lead_obj.phone,
                description=self.request.POST.get('description'),
                website=self.request.POST.get('website')
            )
            account_object.billing_address = address_obj
            if self.request.POST.getlist('assigned_to', []):
                account_object.assigned_to.add(*self.request.POST.getlist('assigned_to'))
            if self.request.POST.getlist('teams', []):
                account_object.teams.add(*self.request.POST.getlist('teams'))
            account_object.save()
        status = self.request.GET.get('status', None)
        if status:
            return redirect('accounts:list')
        else:
            return redirect('leads:list')

    def form_invalid(self, form, address_form):
        return self.render_to_response(

leads/templates/leads_list.html
<table class="table">
   <thead>
      <tr>
         <th width="50%">
            <a href='#'>
            Name
            </a>
            <span class="caret"></span>
         </th>
         <th>
            <a href="#">
            Email
            </a>
         </th>
      </tr>
   </thead>
   <tbody>
      {% ifequal leads|length  0 %}
      <tr>
         <td class="cell">
            NO LEADS FOUND!!
         </td>
      </tr>
      {% endifequal %}
      {% for lead in leads %}
      <tr>
         <td class="cell">
            <a class="cell parentname" id="{{ lead.id }}">
            {{ lead.first_name }}
            </a>
         </td>
         <td class="cell parentemail">
            {{ lead.email }}
         </td>
      </tr>
      {% endfor %}
   </tbody>
</table>

leads/templates/view_leads.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'leads:list' %}">Leads</a></li>
    <li class="breadcrumb-item active">View</li>
  </ol>
</nav>

{%endblock%}
{% block content %}
<div class="main_container" id="maincontainer">
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-8">
      <div class="card">
       
        <div class="card-body" id="datashow">
         <div class="card-title">
          <h5>
            Overview
            <span class="float-right" style="margin-top: 0px">
              <div class="dropdown buttons_row">
                <button class="btn btn-primary dropdown-toggle save" type="button" data-toggle="dropdown">Actions
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'leads:edit_lead' lead_record.id %}" >Edit</a></li>
                  <li><a href="{% url 'leads:leads_convert' lead_record.id %}" class="btn btn-info" role="button">Convert</a></li>
                </ul>
              </div>
            </span>
          </h5>
        </div>
          <div class="row marl">
            <div class="col-md-6">
              <div class="filter_col col-md-12" id="iname">
                <div class="form-group" >
                  <label class="lead_field_label" for="id_name" data-name="name">Name</label>
                  <div class="lead_field" id="lead_name" data-name="name">{{ lead_record.first_name }} {{ lead_record.last_name }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.account_name %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_contact_account" data-name="name">Account Name</label>
                  <div class="lead_field" id ="contact_account" data-name="name">{{ lead_record.account_name }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.title %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_title" data-name="name">Title</label>
                  <div class="lead_field" id="lead_title" data-name="name">{{ lead_record.title }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="lead_field_label" for="id_phone" data-name="name">Phone</label>
                  <div class="lead_field" id="lead_phone" data-name="name">{{ lead_record.phone }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="lead_field_label" for="id_email" data-name="name">Email</label>
                  <div class="lead_field" id="lead_email" data-name="name">{{ lead_record.email }}</div>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="filter_col col-md-12">
                {% if lead_record.status %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_status" data-name="name">Status</label>
                  <div class="lead_field" id="lead_status" data-name="name">{{ lead_record.status }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.source %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_source" data-name="name">Source</label>
                  <div class="lead_field" id="lead_source" data-name="name">{{ lead_record.source }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.website %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_website" data-name="name">Website</label>
                  <div class="lead_field" id="lead_website" data-name="name">{{ lead_record.website }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  {% if lead_record.address.address_line or lead_record.address.street or lead_record.address.city or lead_record.address.state or lead_record.address.postcode or lead_record.address.country %}
                  <label class="lead_field_label" for="id_address" data-name="name" >Billing Address</label>
                  <div class="lead_field" id="lead_address" data-name="name">
                    {{lead_record.address.get_complete_address}}
                  </div>
                  {% endif %}
                </div>
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.description %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_description" data-name="name" >Description</label>
                  <div class="lead_field" id="lead_description" data-name="name">{{ lead_record.description }}</div>
                </div>
                {% endif %}
              </div>
            </div>
            <div class="col-md-12">
                <div class="created_information">
                  Created by <b>{{ lead_record.created_by }}</b> created on <i><b>{{ lead_record.created_on }}</b></i> 
                </div>
              </div>
          </div>
        </div>
        <!-- Comments Section starts-->
       
        <div class="card-body mar-top" id="datashow">
         <div class="card-title view-pad">
          <h5>Comments </h5>
        </div>
          <div class="row marl">
            <div class="col-md-12">
              <form id="comment_form" method="POST" enctype="multipart/form-data">
                <div class="form-group ">
                  <textarea class="form-control" textarea cols="40" rows="3" id="id_comments" name="comment" placeholder="Submit Your Comments Here"></textarea><div><i id="CommentError" style="display:none; color:red"></i></div>
                  </br>
                  <div class="buttons_row">
                  <button class="btn btn-default save" style="text-align: center;" id="comment_submit">Submit</button>
                  </div>
                </div>
                <input type="hidden" value="{{lead_record.id}}" name="leadid">
              </form>
              <ul class="list-group" id="comments_div">
                {% for comment in comments %}
                <li class="list-group-item list-row" id="comment{{comment.id}}">
                  <div class="float-right right-container">
                    <div class="list-row-buttons btn-group float-right">
                      <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
                      <ul class="dropdown-menu text-center">
                        <li>
                          <a class="action" onclick="edit_comment({{comment.id}})">Edit</a>
                        </li>
                        <li>
                          <a class="action" onclick="remove_comment({{comment.id}})">Remove</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="stream-post-container" id="comment_name{{comment.id}}"><pre>{{ comment.comment }}</pre></div>
                  <div class="stream-container">
                    <pre class="float-left">{{ comment.commented_by }}</pre>
                    <pre class="float-right">{{ comment.commented_on }}</pre>
                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="modal fade" id="Comments_Leads_Modal" role="dialog" data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">Update Your Comment</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>

                </div>
                <form id="comment_edit_form" method="POST" >
                  <div class="modal-body">
                    <div class="form-group">
                      <textarea class="form-control" textarea cols="40" rows="3" id="id_editcomment" name="comment" placeholder="Submit Your Comments"></textarea><span><i id="CommentEditError" style="display:none; color:red"></i></span>
                      <input type="hidden" value="{{ lead.id }}" name="leadid">
                      <input type="hidden" value="" name="commentid" id="commentid">
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button class="btn btn-default save" id="comment_edit" type="submit">Update</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- Comments Section Ends-->
      </div>
    </div>
    <tr id="meeting{{ meeting.id }}">
   
  </div>
</div>
{% endblock %}
{% block js_block %}
 <script src="{% static 'js/calls.js' %}"></script>
 <script src="{% static 'js/meetings.js' %}"></script>
 <script type="text/javascript">
$("#comment_form").submit(function (e) {
  e.preventDefault()
  var formData = new FormData($("#comment_form")[0]);
  $.ajax({
    url: "{% url 'leads:add_comment' %}",
    type: "POST",
    data: formData,
    cache: false,
    contentType: false,
    processData: false,
    success: function (data) {
      if (data.error) {
        $("#CommentError").html(data.error).show()
      } else {
        d = new Date(data.commented_on);
        $("#comments_div").prepend("<li class='list-group-item list-row' id='comment" + data.comment_id + "'>" +
          "<div class='float-right right-container'>" +
          "<div class='list-row-buttons btn-group float-right'>" +
          "<button class='btn btn-link btn-sm dropdown-toggle' data-toggle='dropdown' type='button'><span class='caret'></span></button>" +
          "<ul class='dropdown-menu text-center'>" +
          "<li><a class='action' onclick='edit_comment(" + data.comment_id + ")'>Edit</a></li>" +
          "<li><a class='action' onclick='remove_comment(" + data.comment_id + ")''>Remove</a></li></ul></div></div>" +
          "<div class='stream-post-container' id='comment_name"+data.comment_id+"'><pre>"+data.comment+"</pre></div>"+
          "<div class='stream-container'><pre class='float-left'>"+data.commented_by+"</pre><pre class='float-right'>"+d.toGMTString()+"</pre></div>"+
          "<div class='stream-date-container' id='comment_file_div"+data.comment_id+"'><div id='new_comment"+data.comment_id+"'</div></div></li>"
        )
        $("#id_comments").val("")
        alert("Comment Submitted")
        $("#CommentError").html("")
      }
    }
  })
})


function edit_comment(x) {
  $('#Comments_Leads_Modal').modal('show');
  comment = $("#comment_name" + x).text()
  $("#commentid").val(x)
  $("#id_editcomment").val(comment)
}

$("#comment_edit").click(function (e) {
  e.preventDefault()
  var formData = new FormData($("#comment_edit_form")[0]);
  $.ajax({
    url: "{% url 'leads:edit_comment' %}",
    type: "POST",
    data: formData,
    cache: false,
    contentType: false,
    processData: false,
    success: function (data) {
      if (data.error) {
        $("#CommentEditError").html(data.error).show()
      } else {
        $("#comment_name" + data.commentid).html('<pre>' + data.comment + '</pre>')
        $('#Comments_Leads_Modal').modal('hide');
        $("#id_editcomment").val("")
        $("#CommentEditError").html("")
      }
    }
  })
})


function HideError(e) {
  $("#CommentError").hide()
}

function remove_comment(x) {
  var con = confirm("Do you want to Delete it for Sure!?")
  if (con == true) {
    $.post('{% url "leads:remove_comment" %}', {
      "comment_id": x
    }, function (data) {
      if (data.error) {
        alert(data.error)
      } else {
        $("#comment" + data.cid).remove()
      }
    })
  }
}
</script>
{% endblock js_block %}