accounts/urls.py
from django.urls import path
from accounts.views import (
	AccountsListView, CreateAccountView, AccountDetailView, AccountUpdateView,
	AccountDeleteView, AddCommentView, UpdateCommentView, DeleteCommentView)

app_name = 'accounts'

urlpatterns = [
	path('list/', AccountsListView.as_view(), name='list'),
	path('create/', CreateAccountView.as_view(), name='new_account'),
	path('<int:pk>/view/', AccountDetailView.as_view(), name="view_account"),
	path('<int:pk>/edit/', AccountUpdateView.as_view(), name="edit_account"),
	path('<int:pk>/delete/', AccountDeleteView.as_view(), name="remove_account"),
	path('comment/add/', AddCommentView.as_view(), name="add_comment"),
	path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
	path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),
]

cases/urls.py
from django.urls import path
from cases.views import (
    CasesListView, CreateCaseView, CaseDetailView, UpdateCaseView, RemoveCaseView,
    CloseCaseView, SelectContactsView, GetCasesView, AddCommentView,
    UpdateCommentView, DeleteCommentView)

app_name = 'cases'

urlpatterns = [
    path('list/', CasesListView.as_view(), name='list'),
    path('create/', CreateCaseView.as_view(), name='add_case'),
    path('<int:pk>/view/', CaseDetailView.as_view(), name="view_case"),
    path('<int:pk>/edit_case/', UpdateCaseView.as_view(), name="edit_case"),
    path('<int:case_id>/remove/', RemoveCaseView.as_view(), name="remove_case"),

    path('close_case/', CloseCaseView.as_view(), name="close_case"),
    path('select_contacts/', SelectContactsView.as_view(), name="select_contacts"),
    path('get/list/', GetCasesView.as_view(), name="get_cases"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),
]

crm/urls.py
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/', include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),
]

handler404 = handler404
handler500 = handler500

cases/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from accounts.models import Account
from contacts.models import Contact
from common.models import User, Team
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE


class Case(models.Model):
    name = models.CharField(
        pgettext_lazy("Name of the case", "Name"),
        max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(choices=CASE_TYPE, max_length=255, blank=True, null=True, default='')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_on = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='case_assigned_users')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='case_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting", status="Planned")

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Task", status="Planned")

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task").exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Call", status="Planned")

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

cases/forms.py
from django import forms
from cases.models import Case
from common.models import Comment


class CaseForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        case_accounts = kwargs.pop('account', [])
        case_contacts = kwargs.pop('contacts', [])
        super(CaseForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({
            'rows': '6'})
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['account'].queryset = case_accounts
        self.fields['contacts'].queryset = case_contacts
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        self.fields['contacts'].required = False
        for key, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.label

    class Meta:
        model = Case
        fields = ('assigned_to', 'teams', 'name', 'status',
                  'priority', 'case_type', 'account',
                  'contacts', 'closed_on', 'description')

    def clean_name(self):
        name = self.cleaned_data['name']
        case = Case.objects.filter(name__iexact=name).exclude(id=self.instance.id)
        if case:
            raise forms.ValidationError("Case Already Exists with this Name")
        return name


class CaseCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'case', 'commented_by', )

cases/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView, DetailView, ListView, TemplateView, View

from cases.models import Case
from cases.forms import CaseForm, CaseCommentForm
from common.models import Team, User, Comment
from accounts.models import Account
from contacts.models import Contact
from common.utils import PRIORITY_CHOICE, STATUS_CHOICE, CASE_TYPE


class CasesListView(LoginRequiredMixin, TemplateView):
    model = Case
    context_object_name = "cases"
    template_name = "cases.html"

    def get_queryset(self):
        queryset = self.model.objects.all().select_related("account")
        request_post = self.request.POST
        if request_post:
            if request_post.get('name'):
                queryset = queryset.filter(name__icontains=request_post.get('name'))
            if request_post.get('account'):
                queryset = queryset.filter(account_id=request_post.get('account'))
            if request_post.get('status'):
                queryset = queryset.filter(status=request_post.get('status'))
            if request_post.get('priority'):
                queryset = queryset.filter(priority=request_post.get('priority'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CasesListView, self).get_context_data(**kwargs)
        context["cases"] = self.get_queryset()
        context["accounts"] = Account.objects.all()
        context["per_page"] = self.request.POST.get('per_page')
        context["acc"] = int(self.request.POST.get("account")) if self.request.POST.get("account") else None
        context["case_priority"] = PRIORITY_CHOICE
        context["case_status"] = STATUS_CHOICE
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class CreateCaseView(LoginRequiredMixin, CreateView):
    model = Case
    form_class = CaseForm
    template_name = "create_cases.html"

    def dispatch(self, request, *args, **kwargs):
        self.users = User.objects.filter(is_active=True).order_by('email')
        self.accounts = Account.objects.all()
        self.contacts = Contact.objects.all()
        return super(CreateCaseView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(CreateCaseView, self).get_form_kwargs()
        kwargs.update({"assigned_to": self.users, "account": self.accounts,
                       "contacts": self.contacts})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        case = form.save(commit=False)
        case.created_by = self.request.user
        case.save()
        if self.request.POST.getlist('assigned_to', []):
            case.assigned_to.add(*self.request.POST.getlist('assigned_to'))
        if self.request.POST.getlist('teams', []):
            case.teams.add(*self.request.POST.getlist('teams'))
        if self.request.POST.getlist('contacts', []):
            case.contacts.add(*self.request.POST.getlist('contacts'))
        if self.request.is_ajax():
            return JsonResponse({'error': False})
        if self.request.POST.get("savenewform"):
            return redirect("cases:add_case")
        else:
            return redirect('cases:list')

    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse({'error': True, 'case_errors': form.errors})
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(CreateCaseView, self).get_context_data(**kwargs)
        context["teams"] = Team.objects.all()
        context["case_form"] = context["form"]
        context["accounts"] = self.accounts
        context["contacts"] = self.contacts
        context["users"] = self.users
        context["case_types"] = CASE_TYPE
        context["case_priority"] = PRIORITY_CHOICE
        context["case_status"] = STATUS_CHOICE
        context["assignedto_list"] = [
            int(i) for i in self.request.POST.getlist('assigned_to', []) if i]
        context["teams_list"] = [
            int(i) for i in self.request.POST.getlist('teams', []) if i]
        context["contacts_list"] = [
            int(i) for i in self.request.POST.getlist('contacts', []) if i]
        return context


class CaseDetailView(LoginRequiredMixin, DetailView):
    model = Case
    context_object_name = "case_record"
    template_name = "view_case.html"

    def get_queryset(self):
        queryset = super(CaseDetailView, self).get_queryset()
        return queryset.prefetch_related("contacts", "account")

    def get_context_data(self, **kwargs):
        context = super(CaseDetailView, self).get_context_data(**kwargs)
        context.update({"comments": context["case_record"].cases.all()})
        return context


class UpdateCaseView(LoginRequiredMixin, UpdateView):
    model = Case
    form_class = CaseForm
    template_name = "create_cases.html"

    def dispatch(self, request, *args, **kwargs):
        self.users = User.objects.filter(is_active=True).order_by('email')
        self.accounts = Account.objects.all()
        self.contacts = Contact.objects.all()
        return super(UpdateCaseView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(UpdateCaseView, self).get_form_kwargs()
        kwargs.update({"assigned_to": self.users, "account": self.accounts,
                       "contacts": self.contacts})
        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        case_obj = form.save()
        case_obj.assigned_to.clear()
        case_obj.teams.clear()
        case_obj.contacts.clear()
        if self.request.POST.getlist('assigned_to', []):
            case_obj.assigned_to.add(*self.request.POST.getlist('assigned_to'))
        if self.request.POST.getlist('teams', []):
            case_obj.teams.add(*self.request.POST.getlist('teams'))
        if self.request.POST.getlist('contacts', []):
            case_obj.contacts.add(*self.request.POST.getlist('contacts'))
        if self.request.is_ajax():
            return JsonResponse({'error': False})
        return redirect("cases:list")

    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse({'error': True, 'case_errors': form.errors})
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(UpdateCaseView, self).get_context_data(**kwargs)
        context["case_obj"] = self.object
        context["teams"] = Team.objects.all()
        context["case_form"] = context["form"]
        context["accounts"] = self.accounts
        context["contacts"] = self.contacts
        context["users"] = self.users
        context["case_types"] = CASE_TYPE
        context["case_priority"] = PRIORITY_CHOICE
        context["case_status"] = STATUS_CHOICE
        context["assignedto_list"] = [
            int(i) for i in self.request.POST.getlist('assigned_to', []) if i]
        context["teams_list"] = [
            int(i) for i in self.request.POST.getlist('teams', []) if i]
        context["contacts_list"] = [
            int(i) for i in self.request.POST.getlist('contacts', []) if i]
        return context


class RemoveCaseView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        case_id = kwargs.get("case_id")
        self.object = get_object_or_404(Case, id=case_id)
        self.object.delete()
        return redirect("cases:list")

    def post(self, request, *args, **kwargs):
        case_id = kwargs.get("case_id")
        self.object = get_object_or_404(Case, id=case_id)
        self.object.delete()
        if request.is_ajax():
            return JsonResponse({'error': False})
        count = Case.objects.filter(
            Q(assigned_to=request.user) | Q(created_by=request.user)).distinct().count()
        data = {"case_id": case_id, "count": count}
        return JsonResponse(data)


class CloseCaseView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        case_id = request.POST.get("case_id")
        self.object = get_object_or_404(Case, id=case_id)
        self.object.status = "Closed"
        self.object.save()
        data = {'status': "Closed", "cid": case_id}
        return JsonResponse(data)


class SelectContactsView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        contact_account = request.GET.get("account")
        if contact_account:
            account = get_object_or_404(Account, id=contact_account)
            contacts = Contact.objects.filter(account=account)
        else:
            contacts = Contact.objects.all()
        data = {i.pk: i.first_name for i in contacts.distinct()}
        return JsonResponse(data)


class GetCasesView(LoginRequiredMixin, ListView):
    model = Case
    context_object_name = "cases"
    template_name = "cases_list.html"


class AddCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CaseCommentForm
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):

cases/templates/cases.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- heading_create starts here -->
  <div class="row marl heading_create">
    <div class="heading col-md-12">
    <div class="no-gutters row">
      <div class="col-md-6">
      </div>
      <div class="col-md-6">
        <div class="create_new text-right">
          <a href="{% url 'cases:add_case' %}"><i class="fa fa-plus"></i> Add New Case</a>
        </div>
      </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="filter_row row marl">
    <div class="col-md-3 col-xl-2">
      <div class="card">
        <form id="cases_filter" method="POST" action="" >
          <div class="card-body">
            <div class="card-title">Filters</div>
            <div class="row marl">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Name</label>
                  <input type="text" class="form-control" placeholder="Name" name="name" value="{{request.POST.name}}">
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Status</label>
                  <select class="form-control" id="id_status" name="status" >
                    <option value="">--Status--</option>
                    {% for each_status in case_status %}
                    <option value="{{each_status.0}}" {% if request.POST.status %} {% ifequal each_status.0 request.POST.status %}selected{% endifequal %}{% endif %} >{{each_status.1}} </option>
                    {% endfor%}
                  </select>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Priority</label>
                  <select class="form-control" id="id_priority" name="priority" >
                    <option value="">--Priority--</option>
                    {% for each_priority in case_priority %}
                    <option value="{{each_priority.0}}" {% if request.POST.priority %} {% ifequal each_priority.0 request.POST.priority %}selected{% endifequal %}{% endif %}>{{each_priority.1}} </option>
                    {% endfor%}
                  </select>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Account</label>
                  <select class="form-control" id="id_account" name="account">
                    <option value="">--Select Account--</option>
                    {% for ac in accounts %}
                    <option value="{{ac.id}}" {% ifequal acc ac.id %} selected {% endifequal %} >{{ac.name}}</option>
                    {% endfor %}
                  </select>
                  </select>
                </div>
              </div>
              <input type="hidden" id="per_page_field" name="per_page">
              <div class="filter_col text-center col-12">
                <div class="form-group buttons_row text-center">
                  <button class="btn btn-primary save" id="filter_click" type="submit">Search</button>
                  <a href="{% url 'cases:list' %}" id="filter_clear" class="btn btn-default clear">Clear</a>
                </div>
              </div>
            </div>
          </div>
        </form>
        <br clear="all">
      </div>
    </div>
    <div class="col-md-9 col-xl-10">
       <!-- cases_list starts here -->
  <div class="table_container_row row marl no-gutters">
    <div class="col-md-12">
      <div class="card">
        
        <div class="card-body">
        <div class="panel-heading-list card-title">
          List of Cases
          <span class="float-right total_count">{% if show_pageitems %} {% show_pageitems %}{% else %}Total Cases {{ cases|length }}{% endif %}</span>
        </div>
        <div class="table-responsive">
          <table class="table " id="multiselect">
            <thead>
              {% if cases|length > 0 %}

                <tr>
                  <th width="5%">S.No</th>
                  <th width="20%">Name</th>
                  <th width="20%">Account</th>
                  <th width="15%">Status</th>
                  <th width="15%">Priority</th>
                  <th width="15%">Actions</th>
                </tr>
              {% endif %}
            </thead>
            <tbody>
              {% if per_page %}
                {% paginate per_page cases %}
              {% else%}
                {% paginate 10 cases%}
              {% endif %}
              {% for case in cases %}
              <tr class="case_row{{case.id}}" style="text-align:center;">
                <td scope="row">{{ forloop.counter }}</td>
                <td><a href="{% url 'cases:view_case' case.id %}">{{ case.name }}</a></td>
                <td>
                  {% if case.account %}
                    <a href="{% url  'accounts:view_account' case.account.id %}">{{ case.account }}</a>
                  {% else %}
                    No Related Account
                  {% endif %}
                </td>
                <td id="status_id{{case.id}}" status="{{case.status}}">{{ case.status }}</td>
                <td>{{ case.priority }}</td>
                <td class="actions">
                 {#  <a href="{% url 'cases:view_case' case.id %}" class="btn btn-info view"><i class="fas fa-eye"></i> View</a> #}
                  <a href="{% url 'cases:edit_case' case.id %}" class="btn btn-success edit"><i class="fas fa-pencil-alt"></i></a>
                  <a href="{% url 'cases:remove_case' case.id %}" class="btn btn-danger delete remove_case"><i class="fas fa-trash-alt"></i></a>
                  {% if case.status != 'Closed' %}
                  <a onclick="close_case({{case.id}}, '{% url 'cases:close_case' %}')" class="btn btn-warning"><i class="fas fa-times"></i> </a>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
          {% ifequal cases|length 0 %}
            <h6 class="text-center">No Cases Records Found</h6>
          {% endifequal %}
          <div class="marl row text-center">
            {% show_pages %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- cases_list ends here -->
    </div>

  </div>
  <!-- filter_row ends here -->
 
</div>
<!-- main_container ends here -->
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  function close_case(x, url){
    var stat = $("#status_id"+x).text()
    if(stat==="Closed"){
      alert("Case Already Closed")
    }
    else{
      $.post(url, {
       "case_id": x
      }, function(data) {
        location.reload();
      })
    }
  }

  $('.remove_case').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function(e){
    e.preventDefault();
    $('#cases_filter').attr("action", $(this).attr("href"));
    $('#cases_filter').submit();
  });
</script>
{% endblock js_block %}

cases/templates/create_cases.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
{% block extralinks %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'cases:list' %}">Cases</a></li>
    <li class="breadcrumb-item active">{% if case_obj %}Edit{% else %}Create{% endif %}</li>
  </ol>
</nav>

{% endblock %}
{% block content %}
  <form id="submitForm" method="POST" action="" novalidate>
    <div class="overview_form_block row marl">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
             <div class="card-title text-center">
            {% if case_obj %}EDIT{% else %}CREATE{% endif %} CASE
          </div>
            <div class="row marl no-gutters">
              <div class="col-md-6">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_name" class="required">Name{% if case_form.name.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ case_form.name }}
                    <span class="error">{{ case_form.name.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_status" class="required">Status{% if case_form.status.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ case_form.status }}
                    <span class="error">{{ case_form.status.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_priority" class="required">Priority{% if case_form.priority.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ case_form.priority }}
                    <span class="error">{{ case_form.priority.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_case_type">Type of Case{% if case_form.case_type.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ case_form.case_type }}
                    <span class="error">{{ case_form.case_type.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1" class="required">Close Date{% if case_form.closed_on.field.required %}<span class="error">*</span>{% endif %}</label>
                    <div class='input-group date' id='datepicker1'>
                      {{ case_form.closed_on }}
                      <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                    </div>
                    <span class="error">{{ case_form.closed_on.errors }}</span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Assigned Users</label>
                     <select class="assigned_users form-control" name="assigned_to" multiple="multiple">
                      {% for user in users %}
                        <option value="{{user.id}}" {% if user in case_obj.assigned_to.all or user.id in assignedto_list %} selected="" {% endif %}>{{user.email}}</option>
                      {% endfor %}
                    </select>
                    <span class="error">{{ case_form.assigned_to.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_account">Account{% if case_form.account.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ case_form.account }}
                    <span class="error">{{case_form.account.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_contacts">Contacts{% if case_form.contacts.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ case_form.contacts }}
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_description">Description{% if case_form.description.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ case_form.description }}
                    <span class="error">{{ case_form.description.errors }}</span>
                  </div>
                </div>
              </div>
            </div>
            <br clear="all">
          </div>
        </div>
      </div>
      <br clear="all">
      <input type="hidden" id="save_new_form" name="savenewform">
    </div>
    <div class="row marl buttons_row text-center form_btn_row">
      <button class="btn btn-default save" type="submit">Save</button>
      {% if not case_obj %}
        <button class="btn btn-success save savenew" type="submit">Save & New</button>
      {% endif %}
      <a href="{% url 'cases:list' %}" class="btn btn-default clear">Cancel</a>
    </div>
  </form>
{% endblock %}
{% block js_block %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <script type="text/javascript">
    $(function () {
     var date = new Date();
     var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
      $('#id_closed_on').datetimepicker({
          'format': 'YYYY-MM-DD',
          minDate: today
      })
    });

    $(".savenew").on('click', function(e){
      e.preventDefault()
      $("#save_new_form").val('true')
      $('#submitForm').submit()
    });
    $(document).ready(function() {
      $('.assigned_users').select2();
    });

    $('#id_account').change(function(){
    var account = $("#id_account").val()
    $.get("{% url 'cases:select_contacts' %}", {"account":account}, function(data){
      $("#id_contacts").html("")
      $.each(data, function (index, value) {
        $("#id_contacts").append("<option value="+index+">"+value+"</option>")
      });
    })
});
  </script>
{% endblock js_block %}

cases/templates/view_contacts.html
{% for c in contacts %}
	<div class="field case_contacts" data-name="name">{{c.name}}</div>
{% endfor %}