accounts/urls.py
from django.urls import path
from accounts.views import (
	AccountsListView, CreateAccountView, AccountDetailView, AccountUpdateView,
	AccountDeleteView, AddCommentView, UpdateCommentView, DeleteCommentView)

app_name = 'accounts'

urlpatterns = [
	path('list/', AccountsListView.as_view(), name='list'),
	path('create/', CreateAccountView.as_view(), name='new_account'),
	path('<int:pk>/view/', AccountDetailView.as_view(), name="view_account"),
	path('<int:pk>/edit/', AccountUpdateView.as_view(), name="edit_account"),
	path('<int:pk>/delete/', AccountDeleteView.as_view(), name="remove_account"),
	path('comment/add/', AddCommentView.as_view(), name="add_comment"),
	path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
	path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),
]

contacts/urls.py
from django.urls import path
from contacts.views import (
    ContactsListView, CreateContactView, ContactDetailView, UpdateContactView, RemoveContactView,
    GetContactsView, AddCommentView, UpdateCommentView, DeleteCommentView)

app_name = 'contacts'


urlpatterns = [
    path('list/', ContactsListView.as_view(), name='list'),
    path('create/', CreateContactView.as_view(), name='add_contact'),
    path('<int:pk>/view/', ContactDetailView.as_view(), name="view_contact"),
    path('<int:pk>/edit/', UpdateContactView.as_view(), name="edit_contact"),
    path('<int:pk>/delete/', RemoveContactView.as_view(), name="remove_contact"),

    path('get/list/', GetContactsView.as_view(), name="get_contacts"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),
]

crm/urls.py
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/', include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),
]

handler404 = handler404
handler500 = handler500

opportunity/urls.py
from django.urls import path
from opportunity.views import (
    OpportunityListView, CreateOpportunityView, OpportunityDetailView, UpdateOpportunityView,
    DeleteOpportunityView, GetContactView, GetOpportunitiesView, AddCommentView,
    UpdateCommentView, DeleteCommentView)


app_name = 'opportunity'


urlpatterns = [
    path('list/', OpportunityListView.as_view(), name='list'),
    path('create/', CreateOpportunityView.as_view(), name='save'),
    path('<int:pk>/view/', OpportunityDetailView.as_view(), name="opp_view"),
    path('<int:pk>/edit/', UpdateOpportunityView.as_view(), name="opp_edit"),
    path('<int:pk>/delete/', DeleteOpportunityView.as_view(), name="opp_remove"),

    path('contacts/', GetContactView.as_view(), name="contacts"),
    path('get/list/', GetOpportunitiesView.as_view(), name="get_opportunity"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),
]

common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

from common.utils import COUNTRIES, ROLES
import time


def img_url(self, filename):
    hash_ = int(time.time())
    return "%s/%s/%s" % ("profile_pics", hash_, filename)


class User(AbstractBaseUser, PermissionsMixin):
    file_prepend = "users/profile_pics"
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)
    role = models.CharField(max_length=50, choices=ROLES)
    profile_pic = models.FileField(max_length=1000, upload_to=img_url, null=True, blank=True)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def __unicode__(self):
        return self.email


class Address(models.Model):
    address_line = models.CharField(_("Address"), max_length=255, blank=True, null=True)
    street = models.CharField(_("Street"), max_length=55, blank=True, null=True)
    city = models.CharField(_("City"), max_length=255, blank=True, null=True)
    state = models.CharField(_("State"), max_length=255, blank=True, null=True)
    postcode = models.CharField(_("Post/Zip-code"), max_length=64, blank=True, null=True)
    country = models.CharField(max_length=3, choices=COUNTRIES, blank=True, null=True)

    def __str__(self):
        return self.city if self.city else ""

    def get_complete_address(self):
        address = ""
        if self.address_line:
            address += self.address_line
        if self.street:
            if address:
                address += ", " + self.street
            else:
                address += self.street
        if self.city:
            if address:
                address += ", " + self.city
            else:
                address += self.city
        if self.state:
            if address:
                address += ", " + self.state
            else:
                address += self.state
        if self.postcode:
            if address:
                address += ", " + self.postcode
            else:
                address += self.postcode
        if self.country:
            if address:
                address += ", " + self.get_country_display()
            else:
                address += self.get_country_display()
        return address



class Team(models.Model):
    name = models.CharField(max_length=55)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Comment(models.Model):
    case = models.ForeignKey('cases.Case', blank=True, null=True, related_name="cases", on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    commented_on = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    account = models.ForeignKey(
        'accounts.Account', blank=True, null=True, related_name="accounts_comments", on_delete=models.CASCADE)
    lead = models.ForeignKey('leads.Lead', blank=True, null=True, related_name="leads", on_delete=models.CASCADE)
    opportunity = models.ForeignKey(
        'opportunity.Opportunity', blank=True, null=True, related_name="opportunity_comments", on_delete=models.CASCADE)
    contact = models.ForeignKey(
        'contacts.Contact', blank=True, null=True, related_name="contact_comments", on_delete=models.CASCADE)

    def get_files(self):
        return Comment_Files.objects.filter(comment_id=self)


class Comment_Files(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now_add=True)
    comment_file = models.FileField("File", upload_to="comment_files", default='')

    def get_file_name(self):
        if self.comment_file:
            return self.comment_file.path.split('/')[-1]
        else:
            return None

opportunity/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _

from accounts.models import Account
from contacts.models import Contact
from common.models import User, Team
from common.utils import STAGES, SOURCES, CURRENCY_CODES


class Opportunity(models.Model):
    name = models.CharField(pgettext_lazy("Name of Opportunity", "Name"), max_length=64)
    account = models.ForeignKey(Account, related_name='opportunities', on_delete=models.CASCADE, blank=True, null=True)
    stage = models.CharField(
        pgettext_lazy("Stage of Opportunity", "Stage"), max_length=64, choices=STAGES)
    currency = models.CharField(max_length=3, choices=CURRENCY_CODES, blank=True, null=True)
    amount = models.DecimalField(_("Opportunity Amount"), decimal_places=2, max_digits=12, blank=True, null=True)
    lead_source = models.CharField(_("Source of Lead"), max_length=255, choices=SOURCES, blank=True, null=True)
    probability = models.IntegerField(default=0, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    closed_on = models.DateTimeField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='opportunity_assigned_to')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='opportunity_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name

opportunity/forms.py
from django import forms
from opportunity.models import Opportunity
from common.models import Comment


class OpportunityForm(forms.ModelForm):
    probability = forms.IntegerField(max_value=100, required=False)

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        opp_accounts = kwargs.pop('account', [])
        opp_contacts = kwargs.pop('contacts', [])
        super(OpportunityForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({
            'rows': '8'})
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['account'].queryset = opp_accounts
        self.fields['contacts'].queryset = opp_contacts
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        self.fields['contacts'].required = False
        for key, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.label
        self.fields['probability'].widget.attrs.update({
            'placeholder': 'Probability'})

    class Meta:
        model = Opportunity
        fields = (
            'name', 'amount', 'account', 'contacts', 'assigned_to', 'currency',
            'probability', 'teams', 'closed_on', 'lead_source', 'description', 'stage',
        )


class OpportunityCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'opportunity', 'commented_by')

opportunity/templates/create_opportunity.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
{% block extralinks %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'opportunities:list' %}">Opportunities</a></li>
    <li class="breadcrumb-item active">{% if opportunity_obj %}Edit{% else %}Create{% endif %}</li>
  </ol>
</nav>
{% endblock %}
{% block content %}
  <form class= "form_user" method="POST" action="" novalidate>
    <div class="overview_form_block row marl">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
          <div class="card-title text-center">
            {% if opportunity_obj %}EDIT{% else %}CREATE{% endif %} OPPORTUNITY
          </div>
            <div class="row marl no-gutters">
              <div class="col-md-6">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1" class="required">Name{% if opportunity_form.name.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.name }}
                    <span class="error">{{opportunity_form.name.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Account{% if opportunity_form.account.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.account }}
                    <span class="error">{{opportunity_form.account.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Amount</label>
                    <div class="input-group" style="width:100%;">
                      <div class="input-group-btn left-dropdown" style="width:auto;">
                        {{ opportunity_form.currency }}
                        <span class="error">{{opportunity_form.currency.errors}}</span>
                      </div>
                      {{ opportunity_form.amount }}
                      <span class="error">{{opportunity_form.amount.errors}}</span>
                    </div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1" class="required">Stage{% if opportunity_form.stage.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.stage }}
                    <span class="error">{{opportunity_form.stage.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Lead Source{% if opportunity_form.lead_source.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.lead_source }}
                    <span class="error">{{opportunity_form.lead_source.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Probability %{% if opportunity_form.probability.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.probability }}
                    <span class="error">{{opportunity_form.probability.errors}}</span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Assigned Users</label>
                     <select class="assigned_users form-control" name="assigned_to" multiple="multiple">
                      {% for user in users %}
                        <option value="{{user.id}}" {% if user in opportunity_obj.assigned_to.all or user.id in assignedto_list %} selected="" {% endif %}>{{user.email}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <br>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Contacts{% if opportunity_form.contacts.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.contacts }}
                    <span class="error">{{opportunity_form.contacts.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Close Date{% if opportunity_form.closed_on.field.required %}<span class="error">*</span>{% endif %}</label>
                    <div class='input-group date' id='datepicker1'>
                      {{ opportunity_form.closed_on }}
                      <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                    </div>
                    <span class="error">{{opportunity_form.closed_on.errors}}</span>
                  </div>
                </div>
                <div class="form-group col-md-12">
                  <label for="exampleInputEmail1" >Description{% if opportunity_form.description.field.required %}<span class="error">*</span>{% endif %}</label>
                  {{ opportunity_form.description }}
                  <span class="error">{{opportunity_form.description.errors}}</span>
                </div>
              </div>
            </div>
            <br clear="all">
            <input type="hidden" id="save_new_form" name="savenewform">
          </div>
          <!-- overview ends here -->
          <div class="row marl buttons_row text-center form_btn_row">
            <button class=" btn btn-default save" type="submit" id="saveform">Save</button>
            {% if not opportunity_obj %}
              <button class="btn btn-success save savenew" type="submit">Save & New</button>
            {% endif %}
            <a href="{% url 'opportunities:list' %}" class="btn btn-default clear">Cancel</a>
          </div>
        </div>
      </div>
    </div>
  </form>
{% endblock %}
{% block js_block %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <script type="text/javascript">
    $(function () {
       var date = new Date();
       var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $('#id_closed_on').datetimepicker({
            'format': 'YYYY-MM-DD',
            minDate:today
        })
    });

    $(".savenew").on('click', function(e){
      e.preventDefault()
      $("#save_new_form").val('true')
      $('.form_user').submit()
    });
    $(document).ready(function() {
      $('.assigned_users').select2();
      $("#id_contacts").select2();
    });

    $('#id_account').change(function(){
        var Account= $("#id_account").val()
            $.get("{% url 'opportunities:contacts' %}", {"Account":Account}, function(data){
              $("#id_contacts").html("")
              $.each(data, function (index, value) {
                    $("#id_contacts").append("<option value="+index+">"+value+"</option>")
              });
            })
    });

  $("#comment_form").submit(function(e){
      e.preventDefault()
      var formData = new FormData($("#comment_form")[0]);
      $.ajax({
          url : "{% url 'opportunities:add_comment' %}",
          type : "POST",
          data : formData,
          cache: false,
          contentType: false,
          processData: false,
          success: function(data){
              if(data.error){
                  $("#CommentError").html(data.error).show()
              }
              else {
                  $("#comments_div").prepend("<li class='list-group-item list-row' id='comment"+data.com_id+"'>"+
                                     "<div class='pull-right right-container'>"+
                                     "<div class='list-row-buttons btn-group pull-right'>"+
                                     "<button class='btn btn-link btn-sm dropdown-toggle' data-toggle='dropdown' type='button'><span class='caret'></span></button>"+
                                     "<ul class='dropdown-menu pull-right'>"+
                                     "<li><a class='action' onclick='edit_comment("+data.com_id+")'>Edit</a></li>"+
                                     "<li><a class='action' onclick='remove_comment("+data.com_id+")''>Remove</a></li></ul></div></div>"+
                                     "<div class='stream-head-container'> "+data.com_user+" Commented</div>"+
                                     "<div class='stream-post-container' id='comment_name"+data.com_id+"'>"+data.comment+"</div>"+
                                     "<div class='stream-date-container"+data.com_id+"'>"+data.comment_time+"</div></div><div class='stream-date-container' id='comment_file_div"+data.com_id+"'><div id='new_comment"+data.com_id+"'</div></div></li>"
                                     )
                  $("#id_comments").val("")
                  alert("Comment Submitted")
              }
          }
      });
  });


  function edit_comment(x){
      $('#myModal_comment').modal('show');
      comment = $("#comment_name"+x).text()
      $("#commentid").val(x)
      $("#id_editcomment").val(comment)
  }

  $("#comment_edit").click(function(e){
      alert("Heyyyyyyyyyyy")
      e.preventDefault()
      var formData = new FormData($("#comment_edit_form")[0]);
      $.ajax({
          url : "{% url 'opportunities:edit_comment' %}",
          type : "POST",
          data : formData,
          cache: false,
          contentType: false,
          processData: false,
          success:function(data){
              if(data.error) {
                  alert(data.error)
              } else {
                  $("#comment_name"+data.commentid).text(data.comment)
                  $('#myModal_comment').modal('hide');
                  $("#id_editcomment").val("")
              }
          }
      })
  });

  function remove_comment(x){
    var warn = confirm("Are You Sure, you Want to Delete this Comment!?")
    if (warn == true){
      $.post('{% url "opportunities:remove_comment" %}', {"comment_id":x}, function(data){
        if(data.error){
          alert(data.error)
        } else {
          $("#comment"+data.oid).remove()
        }
      })
    }
  }

  function editFun(x) {
      $.ajax({
          type: "POST",
          url: "/opportunities/editdetails/",
          data: {tid: x},
          success: function(data) {
              $("#viewdiv").hide()
              $("#editdiv").show()
              $("#id_name").val(data.name)
              $("#id_stage").val(data.stage)
              $("#id_amount").val(data.amount)
              $("#id_account").val(data.account)
              $("#id_probability").val(data.probability)
              $("#id_close_date").val(data.close_date)
              $("#hiddenval").val(data.eid)
              $("#id_lead_source").val(data.sources)
              $("#id_description").val(data.description)
              contacts = data.contacts.replace("b'", "")
              contacts = contacts.replace(/\\n/g, '')
              contacts = contacts.replace(/\\t/g, '')
              contacts = contacts.replace(/'/g, '')
              contacts = contacts.replace(/}/g, '')
              $("#id_contacts").html(contacts)
          }
      })


      $('#id_account').change(function() {
          var Account = $("#id_account").val()
          $.get("{% url 'opportunities:contacts' %}", {
              "Account": Account
          }, function(data) {
              $("#id_contacts").html("")
              $.each(data, function(index, value) {
                  // console.log(index, value)
                  $("#id_contacts").append("<option value=" + index + ">" + value + "</option>")
              });
          })
      });

  }

  </script>
{% endblock js_block %}

opportunity/templates/opp_contacts.html
<select>
{% for cont in con %}
	<option value="{{cont.id}}" {% for sel in selcon %} {% ifequal cont.id sel.id %} selected {% endifequal%}{% endfor %}>{{cont.name}}</option>
{% endfor %}
</select>

opportunity/templates/opportunities_list.html
<table class="table">
  <thead>
    <tr>
      <th width="50%">
        <a href='#'>
        Name
        </a>
        <span class="caret"></span>
      </th>
      <th>
        <a href="#">
        Stage
        </a>
      </th>
    </tr>
  </thead>
  <tbody>
    {% ifequal opportunities|length  0 %}
    <tr>
      <td class="cell">
        NO OPPORTUNITIES FOUND!!
      </td>
    </tr>
    {% endifequal %}
    {% for opportunity in opportunities %}
    <tr>
      <td class="cell">
        <a class="cell parentname" id="{{ opportunity.id }}">
        {{ opportunity.name }}
        </a>
      </td>
      <td class="cell parentstage">
        {{ opportunity.stage }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

opportunity/templates/opportunity_comments.html
{% for comment in comments %}
<li class="list-group-item list-row" id="comment{{comment.id}}">
  <div class="pull-right right-container">
    <div class="list-row-buttons btn-group pull-right">
      <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
      <ul class="dropdown-menu pull-right">
      <li>
      <a href="{% url 'comment_remove' pk=comment.pk %}"><button type="submit">Submit</button></a>
        <span class="glyphicon glyphicon-remove"></span></a>
      </li>
      </ul>
    </div>
  </div>
  <div class="stream-head-container">{{comment.comment_person}} Commented</div>
  <div class="stream-post-container" id="comment_name{{comment.id}}">{{comment.comment}}</div>
  <div class="stream-date-container">{{comment.comment_time}}</div>
  {% endfor %}