cases/urls.py
from django.urls import path
from cases.views import (
    CasesListView, CreateCaseView, CaseDetailView, UpdateCaseView, RemoveCaseView,
    CloseCaseView, SelectContactsView, GetCasesView, AddCommentView,
    UpdateCommentView, DeleteCommentView)

app_name = 'cases'

urlpatterns = [
    path('list/', CasesListView.as_view(), name='list'),
    path('create/', CreateCaseView.as_view(), name='add_case'),
    path('<int:pk>/view/', CaseDetailView.as_view(), name="view_case"),
    path('<int:pk>/edit_case/', UpdateCaseView.as_view(), name="edit_case"),
    path('<int:case_id>/remove/', RemoveCaseView.as_view(), name="remove_case"),

    path('close_case/', CloseCaseView.as_view(), name="close_case"),
    path('select_contacts/', SelectContactsView.as_view(), name="select_contacts"),
    path('get/list/', GetCasesView.as_view(), name="get_cases"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),
]

common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path, re_path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView, ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView, UserDeleteView, PasswordResetView)
from django.conf.urls.static import static
from django.conf import settings


app_name = 'common'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='remove_user'),

    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/', include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),
]

handler404 = handler404
handler500 = handler500

cases/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from accounts.models import Account
from contacts.models import Contact
from common.models import User, Team
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE


class Case(models.Model):
    name = models.CharField(
        pgettext_lazy("Name of the case", "Name"),
        max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(choices=CASE_TYPE, max_length=255, blank=True, null=True, default='')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_on = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='case_assigned_users')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='case_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting", status="Planned")

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Task", status="Planned")

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task").exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Call", status="Planned")

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

common/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm
from common.models import Address, User


class BillingAddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ('address_line', 'street', 'city', 'state', 'postcode', 'country')

    def __init__(self, *args, **kwargs):
        super(BillingAddressForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['address_line'].widget.attrs.update({
            'placeholder': 'Address Line'})
        self.fields['street'].widget.attrs.update({
            'placeholder': 'Street'})
        self.fields['city'].widget.attrs.update({
            'placeholder': 'City'})
        self.fields['state'].widget.attrs.update({
            'placeholder': 'State'})
        self.fields['postcode'].widget.attrs.update({
            'placeholder': 'Postcode'})
        self.fields["country"].choices = [("", "--Country--"), ] + list(self.fields["country"].choices)[1:]


class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('address_line', 'street', 'city', 'state', 'postcode', 'country')

    def __init__(self, *args, **kwargs):
        super(ShippingAddressForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['address_line'].widget.attrs.update({
            'placeholder': 'Address Line'})
        self.fields['street'].widget.attrs.update({
            'placeholder': 'Street'})
        self.fields['city'].widget.attrs.update({
            'placeholder': 'City'})
        self.fields['state'].widget.attrs.update({
            'placeholder': 'State'})
        self.fields['postcode'].widget.attrs.update({
            'placeholder': 'Postcode'})
        self.fields["country"].choices = [("", "--Country--"), ] + list(self.fields["country"].choices)[1:]


class UserForm(forms.ModelForm):

    password = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'username', 'role', 'profile_pic']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        self.fields['username'].required = True
        self.fields['email'].required = True

        if not self.instance.pk:
            self.fields['password'].required = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'Password must be at least 4 characters long!')
        return password

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.instance.id:
            if self.instance.email != email:
                if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
                else:
                    raise forms.ValidationError('Email already exists')
            else:
                return self.cleaned_data.get("email")
        else:
            if not User.objects.filter(email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
            else:
                raise forms.ValidationError('User already exists with this email')


class LoginForm(forms.ModelForm):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(email=email, password=password)
            if self.user:
                if not self.user.is_active:
                    raise forms.ValidationError("User is Inactive")
            else:
                raise forms.ValidationError("Invalid email and password")
        return self.cleaned_data


class ChangePasswordForm(forms.Form):
    CurrentPassword = forms.CharField(max_length=100)
    Newpassword = forms.CharField(max_length=100)
    confirm = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_confirm(self):
        if len(self.data.get('confirm')) < 4:
            raise forms.ValidationError(
                'Password must be at least 4 characters long!')
        if self.data.get('confirm') != self.cleaned_data.get('Newpassword'):
            raise forms.ValidationError(
                'Confirm password do not match with new password')
        return self.data.get('confirm')


class PasswordResetEmailForm(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("User doesn't exist with this Email")
        return email

templates/base.html
{% load staticfiles %}
{% load compress %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django CRM</title>
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
      {% compress css %}
      <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %} {% endblock %}
</head>
<body class="main_body_bg_color">
<div class="wrapper">
    <!-- header starts here -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
  <a class="navbar-brand" href="{% url 'common:home' %}">Django CRM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% if request.user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <ul class="navbar-nav mr-auto">
       {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
        <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:users_list' %}">Users</a></li>
       {% endif %}
        <li class="nav-item"><a class="nav-link" id="accounts" href="{% url 'accounts:list' %}">Accounts</a></li>
        <li class="nav-item"><a class="nav-link" id="contacts" href="{% url 'contacts:list' %}">Contacts</a></li>
        <li class="nav-item"><a class="nav-link" id="leads" href="{% url 'leads:list' %}">Leads</a></li>
        <li class="nav-item"><a class="nav-link" id="opportunities"href="{% url 'opportunities:list' %}">Opportunities</a></li>
        <li class="nav-item"><a class="nav-link" id="cases" href="{% url 'cases:list' %}">Cases</a></li>
      </ul>

    <ul class="navbar-nav navbar-right my-2 my-lg-0">
      <li class="nav-item dropdown">
          <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button" aria-haspopup="true"
            aria-expanded="false" >
          {% if not request.user.profile_pic %}
          <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
          {% else %}
            {% thumbnail request.user.profile_pic "25x25" as im %}
              <img src="{{ im.url }}">
            {% endthumbnail %}
          {% endif %}
          <b class="caret"></b></a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          {% if request.user.email != "admin@micropyramid.com" %}
          <a class="dropdown-item" href="/change-password/"><i class="fas fa-key"></i> Change Password</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'common:profile' %}"><i class="fas fa-user"></i> Profile</a>
          <a class="dropdown-item" href="{% url 'common:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
        </div>
      </li>
    </ul>
  </div>
  {% endif %}
</nav>
    </header>
    <!-- header ends here -->
    <!-- main_container starts here -->
    <div id="mainbody" class="main_container">
        <!-- breadcrumb starts here -->
        {% block breadcrumb %}
        {% endblock %}
        <!-- breadcrumb ends here -->
        {% block content %}
        {% endblock %}
    </div>
    <!-- main_container ends here -->
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment-with-locales.min.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% block js_block %}

{% endblock js_block %}
<script type="text/javascript">
    $(document).ready(function(){
        word = window.location.pathname.split('/')[1]
        $('#' + word).addClass('active')
    })
</script>
</body>
</html>

templates/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<form id="add_form" method="POST" action="" novalidate>
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
         <div class="card-title">
          Change Password
        </div>
          <div class="row marl no-gutters">
            <div class="col-md-12">
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Old Password</label>
                  <input type="password" class="form-control" name="CurrentPassword" value="{{ request.POST.CurrentPassword }}" placeholder="Old Password">
                </div>
                <span class="error">{{ errors.CurrentPassword }}</span>
                {% if error %}
                <span class="error">{{ error }}</span>
                {% endif %}
              </div>
              {% endif %}
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">New Password</label>
                  <input type="password" class="form-control" name="Newpassword" value="{{ request.POST.Newpassword }}" placeholder="New Password">
                </div>
                <span class="error">{{ errors.Newpassword }}</span>
              </div>
              {% endif %}
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Confirm New Password</label>
                  <input type="password" class="form-control" name="confirm" value="{{ request.POST.confirm }}" placeholder="Confirm Password">
                </div>
                <span class="error">{{ errors.confirm }}</span>
              </div>
              {% endif %}
            </div>
          </div>
          <br>
          <div class="row marl buttons_row form_btn_row text-center">
            <button class="btn btn-default save" type="submit">Change Password</button>
            <button class="btn btn-default"><a href="{% url 'common:profile'%}" style="color:inherit;">Cancel</a></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock content %}

templates/forgot_password.html
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django CRM</title>
    <!-- Bootstrap core CSS -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <!-- Custom styling plus plugins -->
    {% compress css %}
      <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %}{% endblock %}
</head>
<body class="login_register_body">
<div class="container">
    <div class="row marl justify-content-center login_row">
        <div class="col-md-6 col-lg-6 col-xl-4">
            <div class="login_block">
                <div class="login_form_block">
                    <div class="welcome">Forgot Password?</div>
                    <form method="POST" action="">
                        <div class="form-group">
                            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
                        </div>
                        <div class="forgot">Back to login <a href="{% url "common:login" %}">Click Here?</a></div>
                        <button type="submit" class="btn btn-danger">Reset Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
      <a href="{% url "common:logout" %}"><button class="btn btn-primary" type="button">Logout</button></a

templates/login.html
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django CRM</title>
    <!-- Bootstrap core CSS -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <!-- Custom styling plus plugins -->
    {% compress css %}
      <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %}{% endblock %}
</head>
<body class="login_register_body">
<div class="container">
    <div class="row marl justify-content-center login_row">
        <div class="col-md-6 col-lg-6 col-xl-4">
            <div class="login_block">
                <div class="login_form_block">
                    <div class="welcome">Django CRM</div>
                    <form method="POST" action="">
                        <div class="form-group">
                            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
                        </div>
                        <div class="forgot">Forgot Password <a href="{% url "common:password_reset" %}">Click Here?</a></div>
                        {% if error %}
                            <p class="error">{{ message }}</p>
                        {% endif %}
                        <button type="submit" class="btn btn-danger">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content%}

<!-- OPPORTUNITY VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body" id="datashow">
            <div class="panel-heading card-title view-pad text-center">
              <h5>
                Profile
                <!-- <span class="float-right" style="margin-top: 0px">
                  <div class="dropdown buttons_row">
                    <button class="btn btn-primary dropdown-toggle save" type="button" data-toggle="dropdown">Actions
                    <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="#" >Edit</a></li>
                      <li class="delete_contact"><a href="#" id="remove_contact">Remove</a></li>
                    </ul>
                  </div>
                </span> -->
              </h5>
              <a href="{% url 'common:edit_user' user_obj.id %}" class="btn btn-success edit">Edit</a>
            </div>
            <div class="row marl no-gutters">
              <div class="col-md-8">
                {% if user_obj.first_name %}
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_name" data-name="name">Name</label>
                    <div class="contact_field" id="contact_name" data-name="name">{{ user_obj.first_name }} {{ user_obj.last_name }}</div>
                  </div>
                </div>
                {% endif %}
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_contact_account" data-name="name">UserName</label>
                    <div class="contact_field" id="contact_account" data-name="name">{{ user_obj.username }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_email" data-name="name">Email</label>
                    <div class="contact_field" id="contact_email" data-name="name">{{ user_obj.email }}</div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="profile_pic">
                  {% if user_obj.profile_pic %}
                    {% thumbnail request.user.profile_pic "125x125" as im %}
                    <img src="{{ im.url }}">
                    {% endthumbnail %}
                  {% else %}
                  <img src="https://cdn.dribbble.com/users/99875/screenshots/4353558/2018-03-01biker_site-2.gif" />
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- OPPORTUNITY VIEW ENDS -->
{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% block content %}
<h1>Registration</h1>
    <form method="POST" class="user-form">
        {{ reg_form.as_p }}
        <button class="btn btn-primary" type="submit">Submit</button></form>
{% endblock %}